### ISSUE TITLE
Questions on Week 5, Part 1 code

### ISSUE THREAD

**Issue by egemenpamukcu** [macss-modeling/General-Questions#13]
Hello Professor, I have some questions on the first part of the code on nonlinear estimation. 

**1)**
In the part where we run CV to decide on the optimal number of knots in the natural spline model we define a function names `vote_spline()` which initially generates the following model: 

```
model <- glm(vote96 ~ ns(age, df = df),
               data = analysis(splits))
```

My question is why don't we use `family = binomial` parameter inside the `glm()` function above? Doesn't that specify the logistic regression model? It seems to me that we are building a linear regression model instead of logistic regression unlike the prior examples. 

**2)**
Also related to this: when I include the `family = binomial` parameter in `glm()`, the `.fitted` column generated by the `augment()` function includes values below 0 or greater than 1.  I thought logistic regression model was supposed to prevent that. What am I missing?

**3)**
Another question I have is about the following piece of code:
```
tibble(
  terms = c(1, 5, 10),
  models = map(terms, ~ glm(y ~ bs(x, df = . + 3), data = sim_piece)),
  pred = map(models, augment, newdata = sim_piece)
) 
```
What is the purpose of the `~` character before the `glm()` here? I understand that `map()` applies a function to every item in a list, but can you explain what it does in this case?

**Comment by Yutong0828** [comment]
Hi professor, I have a few questions about the natural splines. 
1. Why does the graph demonstrate that optimal number of knots is 7? It seems that the 10-fold CV error is the lowest at 20 and 25.
![image](https://user-images.githubusercontent.com/72175632/107477487-c47fe980-6bb2-11eb-8631-2df8c8ead4bf.png)

2. How can we specify the degrees of the polynomial? For example, in this piece of cold, we only specify the degrees of freedom, but does not mention whether the model should be cubic or not.
`glm(vote96 ~ ns(age, df = 10), data = mh, family = binomial) %>%
  cplot("age", what = "prediction", n = 101, draw = FALSE) %>%`

Thank you very much!

**Comment by pdwaggoner** [comment]
@Yutong0828 Thanks for the questions.

1. I noted in the code you may get different values than me. Consider emptying the environment, and trying again. You will get a different set. The results I printed were those I got on my local machine. They are for demonstrative purposes only. Explore a bit. 
2. The degrees of freedom are the polynomial degrees in natural piecewise cubic splines. For example, fitting a cubic spline with df = 1, gives a linear/straight line as a linear regression to polynomial degree = 1 would. See this in action by running the following toy code: 

```{r}
# set up some data
x <- seq(0, 1, length=100)

# fit many splines of various degrees
par(mfrow= c(2, 2))
matplot(splines::ns(x,df=1), ylab= "", type='l', main="Df = 1")
matplot(splines::ns(x,df=2), ylab= "", type='l', main="Df = 2")
matplot(splines::ns(x,df=3), ylab= "", type='l', main="Df = 3")
matplot(splines::ns(x,df=4), ylab= "", type='l', main="Df = 4")
```

**Comment by pdwaggoner** [comment]
@egemenpamukcu Thanks for the questions.

1. Great question. I did this for convenience to demonstrate a simple search over knots. This is why you got odd estimates per question #2. But, in practice this shouldn't be done. I was demonstrating a different point. That's why I didn't make that choice anywhere else in the code. Thanks. 
2. `map()` maps to every item in a list *or in an atomic vector*. Thus, the `~` is for mapping an entire model to different `terms`.
