### ISSUE TITLE
Conceptual Questions about the step functions

### ISSUE THREAD

**Issue by YijingZhang-98** [macss-modeling/General-Questions#14]
Hi Professor, 
I did get what does the **fit a different constant**  in the sentence "Step functions split the range of X into bins and **fit a different constant to each bin**."  refers to. Does it mean we construct an indicator function for each bin? or does it mean we would estimate a coefficient for each bin? 

Thank you.

**Comment by bjcliang-uchi** [comment]
Hi Yijing, I am not quite clear about your question. What is the difference between constructing an indicator function and estimating a coefficient?

**Comment by pdwaggoner** [comment]
@YijingZhang-98 It's a bit of both. Note the construction of equation 2 in the nonlinear1 lecture notes for this week (that is, part 1). If the indicator for a given region in X, say region 1, evaluates to 1, then \beta_1 is the effect in that region. So a unique \beta for a unique region, dependent on values in X. But importantly, in the general form, the function gives a *constant* effect in each bin. So while effects are different *between* bins (defined by \beta_k for the kth region), the effects *within* each region is constant. For example, see one of the simplest step functions (the rectangular step function) here: https://en.wikipedia.org/wiki/Rectangular_function

**Comment by YijingZhang-98** [comment]
That's very clear. Thank you!
