### ISSUE TITLE
Questions about nonlinear_pt2 code

### ISSUE THREAD

**Issue by Yutong0828** [macss-modeling/General-Questions#15]
Hi professor, I received an error message when running this piece of code:

`# animate to see differences for Ep kernel over many bandwidths in real time; takes a couple minutes to run, but it's worth it!
animate(kernel_bandwidth, nframes = length(seq(from = 1, to = 15, by = .1)) * 2)`
 
The error message is:
```
Error in transform_path(all_frames, next_state, ease, params$transition_length[i],  : 
  transformr is required to tween paths and lines
```

It does not take my RStudio a couple minutes to run, but the error appears immediately, and I couldn't figure out why. Do you have any idea of what's happening? Thank you very much!

**Comment by pdwaggoner** [comment]
@Yutong0828 This means you need to load the `transformr` package to allow the animation to run. It's a thing with "transitioning states". That is, individual, quick pictures are essentially comprising each of the animated moments in this approach to animation in R. A few packages are needed to ensure those states/pictures are knitted together to cleanly to effectively animate over some defined range of a value as in our case. So, just run the following code the **first time**:

```{r}
install.packages("transformr")
library(transformr)
```

Then, every R session **thereafter**, simply run/add to the front end of your R script:

```{r}
library(transformr)
```

**Comment by xjinzheng** [comment]
Hi professor, I had the same issue here. But after I imported the above libraries, the `animate()` just generated tons of pngs. May I ask is there something wrong, and how can I make them an animation?

**Comment by pdwaggoner** [comment]
https://stackoverflow.com/questions/58991580/gganimate-returns-png-files-but-no-animated-object
