### ISSUE TITLE
Dropping all missing values drops entire table in Python

### ISSUE THREAD

**Issue by k-partha** [macss-modeling/General-Questions#2]
Coding __ NA __ as a missing value in Python drops the entire table. How should I proceed?
![image](https://user-images.githubusercontent.com/64325241/105740650-6347ed00-5f07-11eb-897e-832b31ea0200.png)

**Comment by pdwaggoner** [comment]
As noted in the other issue: 

> Short of answering the questions for you and other than the direction and code I've shared, my best advice would be to progress with the question based on what you have, whether that's a smaller or larger data set than what I have described here and in the problem set. And then justify your selections and process. It's better to have something than nothing. So keep working with it, and trying some different options (e.g., hunt for different indicators of what may reflect a missing case, like `998`, `_NA_`, `NA`, `.`, and so on)), and do your best.

**Comment by k-partha** [comment]
Dear Professor, I did try to tinker around extensively with the NA codings - as I mentioned in my previous issue. My concern here is that the median of 39.5 was not being obtained despite tinkering (due to small differences between pandas/ stock R/ tidyverse). Would a different median be considered as a "correct" answer given appropriate justification?

**Comment by pdwaggoner** [comment]
Great question. Yeah, these types of nuanced differences are much less important to me than your code and process. Note the wording of the question:

> 9. (15 points) The median for feelings toward Obama (`ftobama`) from the ANES data with all NAs dropped that you previously created, is 39.5. Using a package or any function/method you'd like, bootstrap the standard error of our statistic of interest (which is the median in this case) based on 1000 draws from the data. You might consider writing a simple helper function to speed along the bootstrapping process, but this is up to you of course. Then, construct the 95% confidence interval around your bootstrapped estimate. Report your results and offer a few points of discussion. *Respond with a few sentences.*

So I am asking you to: 1. bootstrap the SE of the median, 2. construct 95% CIs around this estimate. 3. Report your process (code, output) and discuss. That's it. So if your median is different than mine, then that's fine. Tell me why you think that is, and point to your solution as a viable solution. I won't penalize based on small nuances like this. I hope this helps a bit. 

CC @bjcliang-uchi @Yilun0221 @tianyueniu

**Comment by k-partha** [comment]
Thanks! This was precisely my concern!
