### ISSUE TITLE
Question About Week 7 Lecture Notes

### ISSUE THREAD

**Issue by Raychanan** [macss-modeling/General-Questions#22]
Dear Professor Waggoner, I could not find the links to week 7 lecture notes or pre-recorded lectures. May I ask if you decided not to distribute them anymore? Thanks!

**Comment by pdwaggoner** [comment]
Hi - as noted a few weeks ago, I am no longer posting pre-recorded lectures. But the lecture notes are posted on canvas under the appropriate page in the appropriate modules (week 7 currently)
