### ISSUE TITLE
In ps4, why SD not equals the square root of variance??

### ISSUE THREAD

**Issue by jinfei1125** [macss-modeling/General-Questions#25]
Hi, I am confused by the data of question 1: in my understanding, SD is the square root of the variance, but here they don't follow this rule. So in question 2 if we use var = SD^2 or var = var 

I am also thinking about the degree of freedom stuff, because sometimes we calculate the variance by 1/(n-1)sum((x_i - x_mean)^2). But I think the relationship of SD = sqrt(Var) doesn't change?

![image](https://user-images.githubusercontent.com/72103935/109599031-83f7f980-7ae8-11eb-83b2-d53977e88731.png)

Thanks in advance for any explanations!

**Comment by pdwaggoner** [comment]
Look closely at the question wording: *total variance*. That is, you are given individual variance for each PC. And yes, standard deviation is a measure of variance too, but it's a different type of variance: variance of projected points' positions along a given PC. So think carefully about what *total* is referencing in this question, and try not to over think it.
