### ISSUE TITLE
About the Final Exam

### ISSUE THREAD

**Issue by YijingZhang-98** [macss-modeling/General-Questions#29]
Dear Professor, I was wondering may we know the format of the final exam. Is it like the quiz, that consisted of multiple-choice questions? Or other types of questions? and do we have computational tasks? Also, I would appreciate it if you could kindly provide suggestions on how to prepare for the final exam. Thank you!

**Comment by pdwaggoner** [comment]
Hi - as noted several times (as well as in the syllabus both in the description and in the calendar for this week), I will release details on the final exam tomorrow, including a study guide. Stand by. Thanks!
