### ISSUE TITLE
Party ID ? Pid3?

### ISSUE THREAD

**Issue by FranciscoRMendes** [macss-modeling/General-Questions#30]
Hello - can you please clarify where do we get the party from? From previous exercises we know that pid3 is the party with 1 being democrat , others being "others". can you please clarify which number corresponds to which party?

**Comment by ddlee19** [comment]
https://electionstudies.org/wp-content/uploads/2016/02/anes_pilot_2016_CodebookUserGuide.pdf

Doing a Ctrl+F for "pid3" on the document provided in the PDF of the pset should give you the answer.

**Comment by FranciscoRMendes** [comment]
Right thank you, I wanted to verify that these two are indeed identical as the link provided is for :
https://electionstudies.org/wp-content/uploads/2016/02/anes_pilot_2016_qnaire.pdf 
(which does not mention pid3).

**Comment by pdwaggoner** [comment]
https://electionstudies.org/wp-content/uploads/2016/02/anes_pilot_2016_CodebookUserGuide.pdf

**Comment by pdwaggoner** [comment]
Codebook is slightly different from the questionnaire, as things are *asked* and *coded* differently sometimes when translating from a survey to a dataset. Thanks for the help though @ddlee19 !
