### ISSUE TITLE
Clarifying Questions about the PS1-7 plots

### ISSUE THREAD

**Issue by YijingZhang-98** [macss-modeling/General-Questions#4]
Hi Professor and TA, I have a clarifying question about question 7 in the problem set 1.

We have three understanding about the required plots, including:
(1) Draw three plots, the first one compares the distribution of ftobama of two bootstrapped sample, the second one compares the fttrump of two bootstrapped samples, and the third one compares the ftobama and fttrump of the original data set.

(2) Draw two plots, the first one compares the distribution of ftobama of the two bootstrapped samples and the the original dataset; the second one compares the distribution of fttrump of the two bootstraps and the original dataset.

(3) Draw three plots, the first compares the distributions of ftobama and fttrump of the first bootstrapped sample, the second compares the ftobama and fttrump of the second bootstrapped sample, and the third one compares the ftobama and fttrump of the original dataset.

The question stated as: 
_7. (10 points) Recall bootstrapping involves a process of drawing random samples of size n through sampling with replacement. Using the 2016 ANES data we’ve used a few times already, **create and plot two bootstrapped samples manually** (i.e., not using a function like boot() ). For reference, **also plot the original data set to compare distributions of feelings toward Trump (fttrump) versus feelings toward Obama (ftobama).** Note: When loading the ANES data, you may simply drop the NAs, rather than impute, for ease (though in practice, this strategy isn’t recommended)._

Thanks for your help.

**Comment by pdwaggoner** [comment]
I think you're over-thinking this. The wording refers to the axes: plot feelings toward trump (x-axis) *versus* feelings toward obama (y axis). do this for the full sample as a reference point. Then use "bootstrapping" (sampling with replacement of size n) and display. Then, literally do the same thing again. That is manually create three bootstrapped samples and compare these to the reference distribution. Three plots side by side.
