### ISSUE TITLE
Don't understand the variable `splits` in 1.26 inclass code

### ISSUE THREAD

**Issue by jinfei1125** [macss-modeling/General-Questions#5]
Hi, in today's bootstrap procedure, we have:
```
## helper fun
mean_ice <- function(splits) {
  x <- analysis(splits)
  mean(x$sim)
}

ice_boot <- ice %>% 
  bootstraps(1000) %>% 
  mutate(mean = map_dbl(splits, mean_ice))

boot_sem <- sd(ice_boot$mean)
```

I don't understand where we got the variable `splits` in `map_dbl(splits, mean_ice) `before... There is no definition of it. When I use `? splits` in R command line, it says `No documentation for ‘splits’ in specified packages and libraries`, I know that `map_dbl()` returns a double vector. But where do we got `splits`?

Thanks in advance!

**Comment by pdwaggoner** [comment]
Splits is not a variable, but an argument defined by the function. You'll see when creating the bootstrapped samples via `bootstraps()` from the rsample package, each sample is called a "split". So this is written to say, take each of those samples ("splits") and calculate the mean of each. So we are mapping `mean()` to each resample.
