### ISSUE TITLE
Do we need to pull request for ps1?

### ISSUE THREAD

**Issue by jinfei1125** [macss-modeling/General-Questions#6]
Hi, according to Benjamin's [GitHub workflow tutorial video](https://cfss.uchicago.edu/faq/homework-guidelines/#homework-workflow), we should create a pull request on the original repository to turn in the assignment. However, since our ps1 repository is directly under the repository [macss-modeling](https://github.com/macss-modeling), I don't find a place to create a pull request to the base repository. I guess only pushing our pdf to our private ps1 repository is enough?

**Comment by pdwaggoner** [comment]
Yeah, that workflow is excellent, but it was created prior to using GH classroom, so no need for a PR. Just make all commit necessary to ensure the final PDF is in your version of the private repo and you'll be good to go.
