### ISSUE TITLE
Few conceptual questions about indicator function regarding KNN classifier and decision boundary

### ISSUE THREAD

**Issue by ddlee19** [macss-modeling/General-Questions#9]
![image](https://user-images.githubusercontent.com/17442853/107109519-cf2f2d00-6806-11eb-93df-e2f7bfc71035.png)

3. Doesn't a kNN classifier have 2 hyperparameters - the num of neighbors (k) and type of distance (l1, l2) rather than 1?

Thanks,
Daniel

**Comment by pdwaggoner** [comment]
Thanks for the questions. 

1. This is equation 2.12 on p. 39 of ISL. The interpretation is 0 = correct, 1 = incorrect.
2. The boundary in 26 is the Bayes decision boundary based on the simulation. That turns to a dotted line for comparison in subsequent slides to compare versions of kNN (varying k) to the Bayes boundary we found/simulated initially in slide 26. 
3. Technically, you are right, but it is widely agreed up on that kNN is the simplest classifier with a single hyperparameter (e.g., see the general form on p. 14 in eq 2.8). There is only a formally *defined* hyperparameter and you'd likely get push back if you declared knn to be a model with two hyperparameters; but again, you are right that a distance metric is also required.
